version: '3'
services:
  chatbot_vendedor:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:6000"
    volumes:
      - ./bot_sessions:/app/bot_sessions
    working_dir: /app
    restart: always